apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.db_name }}-${{ values.db_type_short }}-vm
  description: "${{ values.db_type }} database VM provisioned via Ansible Automation Platform"
  annotations:
    dbaas/connection-url: "${{ values.db_standard_url }}"
    dbaas/cli-command: "${{ values.db_cli_command }}"
  tags:
    - database
    - ${{ values.db_type_short }}
spec:
  type: database
  owner: ${{ values.owner }}
  lifecycle: production
